services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
      - "9229:9229"
    volumes:
      - app:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - inventory_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  inventory_data:
  node_modules:
  app:
